server:
  port: 80

spring:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      enabled: true
      routes:
        - id: family
          uri: http://127.0.0.1:39090
          predicates:
            - name: Path
              args:
                - /base/**
          filters:
            - StripPrefix=1
        - id: ai
          uri: http://127.0.0.1:39091
          predicates:
            - name: Path
              args:
                - /ai/**
          filters:
            - StripPrefix=1

logging:
  file:
    path: /log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: info


knife4j:
  gateway:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    strategy: manual
    routes:
      - name: family
        url: /base/v3/api-docs?group=default
        service-name: family
        context-path: /base
        order: 1
      - name: ai
        url: /ai/v3/api-docs?group=default
        service-name: family
        context-path: /ai
        order: 2

family-gateway:
  jwt:
    ignoreUrlSet:
      - /user/login
      - /user/register
      - /user/refresh
    authorization: Authorization
    accessKey: MTIzNDU2
    refresh-key: MTIzNDU2
    access-token-expire-time: 300000
    refresh-token-expire-time: 2592000000