server:
  port: 39090
  http2:
    enabled: true
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-keep-alive-requests: 100
    keep-alive-timeout: 10000
    accesslog:
      enabled: true
      directory: /log/${spring.application.name}
      prefix: access_log
      suffix: .log
      encoding: utf-8

spring:
  profiles:
    active: dev
  application:
    name: familyBaseModel

mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.egon.familyaibutler.family
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  file:
    path: /log/${spring.application.name}
  config: classpath:log/logback-spring.xml
  level:
    root: info
