server:
  port: 39090
  http2:
    enabled: true
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
    max-connections: 10000
    accept-count: 1000
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-keep-alive-requests: 100
    keep-alive-timeout: 10000
    accesslog:
      enabled: true
      directory: /log/${spring.application.name}
      prefix: access_log
      suffix: .log
      encoding: utf-8

spring:
  main:
    banner-mode: off
  cache:
    type: none
  profiles:
    active: dev
  application:
    name: familyBaseModel
  datasource:
    hikari:
      connection-timeout: 2000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 200000
      auto-commit: true
      max-lifetime: 1800000
      connection-test-query: select 1
      pool-name: FamilyHikariCP
      validation-timeout: 3000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      indent-output: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      timeout: 30000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    banner: false
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false
  type-aliases-package: top.egon.familyaibutler.family.enums

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.egon.familyaibutler.family
knife4j:
  enable: true
  documents:
    - name: 'default'
      group: 'v0.1'
      locations: top.egon.familyaibutler.family.controller
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true
    footer-custom-content: MIT License | Copyright  2025-[FamilyAiBulter](https://github.com/AllenDEricDAlexander/FamilyAiBulter)
  basic:
    enable: true
    username: admin
    password: 123456


logging:
  file:
    path: /log/${spring.application.name}
  config: classpath:log/logback-spring.xml
