knife4j:
  production: false

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/familyaibutler
    username: postgres
    password: mqa010225@gmail
    driver-class-name: org.postgresql.Driver