server:
  port: 39090
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1
spring:
  application:
    name: family



springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: top.egon.familyaibutler.family
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    root: info
